---
# file: roles/essential/tasks/main.yml

- name: ensure firewalld is running
  service:
    name: firewalld
    enabled: yes
    state: started
  tags:
    - firewall

- name: ensure postgresql server is available
  firewalld:
    immediate: yes
    permanent: yes
    service: postgresql
    state: enabled
  tags:
    - firewall

- include: docker.yml
